services:
  mongo:
    image: mongo:latest
    command: --profile 2
    container_name: parrot_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: "redis/redis-stack:latest"
    container_name: parrot_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    environment:
      - REDIS_ARGS="--protocol 3"

networks:
  lavalink:
    name: lavalink

volumes:
  mongo_data:
  redis_data: